# See https://github.com/actions/labeler

example:
  - examples/**/*

'🚨 action':
  - .github/workflows/**

script:
  - packages/proxima/**

client:
  - packages/client/**

next:
  - packages/client/**
