# Automatically labels PRs based on the configuration file
# you are probably looking for 👉 `.github/labeler.yml`
name: Label PRs

on:
  pull_request_target:
    types: [assigned, opened, synchronize, reopened]

jobs:
  triage:
    runs-on: ubuntu-latest
    # Sanity check for copy-paste errors
    if: github.repository_owner == 'proximahq'
    steps:
      - uses: actions/labeler@v4
        with:
          repo-token: '${{ secrets.GITHUB_TOKEN }}'
          sync-labels: true
